language: python
env:
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5.1
python:
  - "2.6"
  - "2.7"
  - "3.3"
install: 
  - "pip install -q django==$DJANGO_VERSION"
  - "pip install -r requirements.txt --use-mirrors"
script: "py.test ."
matrix:
  exclude:
    - python: 3.3
      env: DJANGO_VERSION=1.4.5
